language: node_js

node_js:
  - 'stable'

sudo: false

cache:
  yarn: false
  directories:
    - 'node_modules'

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION -f coverage/coverage-final.json
